language: ruby
rvm:
  - 2.3.1
  - 2.2.3
  - 2.1.4
  - 2.0.0
  - ruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
