language: ruby
rvm:
  - 2.6.3
  - 2.3.3
  - ruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.3.3
      gemfile: gemfiles/6.0.gemfile

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
