language: ruby
rvm:
  - 2.1.4
  - 2.0.0
  - 1.9.3
  - ruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
